import { Inter } from "next/font/google";
import "./globals.css";
import AppContextProvider from "./Context";
import Loading from "./components/Loading";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContextProvider>
          {children}
          <Loading />
          <ToastContainer />
        </AppContextProvider>
      </body>
    </html>
  );
}
